# Generated by Django 5.2.8 on 2025-11-30 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_merge_20251129_2254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('result_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='organizations.organization')),
            ],
            options={
                'db_table': 'elections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elections.election')),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manifesto', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.position')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['organization', 'status'], name='elections_organiz_cf940d_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status'], name='elections_status_eb3191_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['start_at', 'end_at'], name='elections_start_a_c20ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['election', 'order_index'], name='positions_electio_74e943_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('election', 'title')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['position'], name='candidates_positio_f788c0_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['user'], name='candidates_user_id_5d06f1_idx'),
        ),
    ]
