# Generated by Django 5.2.8 on 2025-11-29 21:48

from django.db import migrations

def set_organization_owners(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Organization = apps.get_model('organizations', 'Organization')
    
    # Get the first superuser or create one if none exists
    try:
        admin = User.objects.filter(is_superuser=True).first()
        if not admin:
            admin = User.objects.create_superuser(
                email='admin@example.com',
                password='adminpass123',
                first_name='Admin',
                last_name='User'
            )
        
        # Set all organizations to be owned by the admin
        Organization.objects.filter(owner__isnull=True).update(owner=admin)
    except Exception as e:
        print(f"Error setting organization owners: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationmember_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_organization_owners, migrations.RunPython.noop),
    ]
