# Generated by Django 5.2.8 on 2025-11-29 21:53

from django.db import migrations
from django.contrib.auth.hashers import make_password

def set_default_owner(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Organization = apps.get_model('organizations', 'Organization')
    
    # Get the first superuser or create one if none exists
    admin = User.objects.filter(is_superuser=True).first()
    if not admin:
        admin = User.objects.create(
            email='admin@example.com',
            password=make_password('adminpass123'),
            first_name='Admin',
            last_name='User',
            is_staff=True,
            is_superuser=True,
            role='super_admin',
            status='active'
        )
    
    # Set any null owners to the admin
    Organization.objects.filter(owner__isnull=True).update(owner=admin)

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_set_organization_owners'),  # Update this to the previous migration
    ]

    operations = [
        migrations.RunPython(set_default_owner, migrations.RunPython.noop),
        # Add the AlterField operation here after running the data migration
    ]