# Generated by Django 5.2.8 on 2025-11-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_owner'),
        ('organizations', '0005_make_owner_required'),
    ]

    operations = [
    ]
