# Generated by Django 5.2.8 on 2025-11-30 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('organizations', '0006_merge_20251129_2254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.position')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='organizations.organizationmember')),
                ('voter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['election', 'position'], name='votes_electio_09276f_idx'), models.Index(fields=['candidate'], name='votes_candida_da1a33_idx'), models.Index(fields=['voter'], name='votes_voter_i_706843_idx'), models.Index(fields=['voter_user'], name='votes_voter_u_4f8e91_idx'), models.Index(fields=['created_at'], name='votes_created_cd32d2_idx'), models.Index(fields=['vote_token'], name='votes_vote_to_f0aec4_idx')],
            },
        ),
    ]
